import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Footer2 from "@/components/ui/footer";


const oswald = Oswald({weight:'500', subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={oswald.className}
      >
        {children}
        <Footer2/>
      </body>
    </html>
  );
}
